In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

import scipy
from scipy.stats import spearmanr

# Math
import math

# Plot imports
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

# Machine Learning Imports
from sklearn.preprocessing import scale
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split

# For evaluating our ML results
from sklearn import metrics

# Dataset Import
import statsmodels.api as sm

C:\Users\egede\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\egede\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [2]:
df = pd.read_csv('fifa_data2.csv')

In [3]:
df.head()

name  age                     league  height_cm  weight_kg  \
0  Cristiano Ronaldo   32  Spanish Primera División        185         80   
1           L. Messi   30  Spanish Primera División        170         72   
2             Neymar   25             French Ligue 1        175         68   
3         L. Suárez   30  Spanish Primera División        182         86   
4           M. Neuer   31          German Bundesliga        193         92   

   potential  pas accuracy  shooting  def  phy   ...    stamina  strength  \
0         94            90        93   33   80   ...         92        80   
1         93            89        90   26   61   ...         73        59   
2         94            92        84   30   60   ...         78        53   
3         92            82        90   42   81   ...         89        80   
4         92            91        90   60   91   ...         44        83   

   long_shots  aggression  interceptions  positioning  vision  penalties  \
0          92          63             29           95      85         85   
1          88          48             22           93      90         78   
2          77          56             36           90      80         81   
3          86          78             41           92      84         85   
4          16          29             30           12      70         47   

   composure  marking  
0         95       22  
1         96       13  
2         92       21  
3         83       30  
4         70       10  

[5 rows x 38 columns]

In [4]:
df = df[['pas accuracy', 'shooting', 'age', 'free_kick_accuracy','ball_control','balance','vision','jumping','strength','positioning','crossing','heading_accuracy','finishing']]

In [5]:
df.head()

pas accuracy  shooting  age  free_kick_accuracy  ball_control  balance  \
0            90        93   32                  76            93       63   
1            89        90   30                  90            95       95   
2            92        84   25                  84            95       82   
3            82        90   30                  84            91       60   
4            91        90   31                  11            48       35   

   vision  jumping  strength  positioning  crossing  heading_accuracy  \
0      85       95        80           95        85                88   
1      90       68        59           93        77                71   
2      80       61        53           90        75                62   
3      84       69        80           92        77                77   
4      70       78        83           12        15                25   

   finishing  
0         94  
1         95  
2         89  
3         94  
4         13

In [6]:
# Create check function
def forvet_check(x):
    if x >= 70:
        return 1
    else:
        return 0

# Apply to DataFrame
df['forvet'] = df['finishing'].apply(forvet_check)

In [7]:
df=df.drop('finishing',axis=1)

In [8]:
df.head()

pas accuracy  shooting  age  free_kick_accuracy  ball_control  balance  \
0            90        93   32                  76            93       63   
1            89        90   30                  90            95       95   
2            92        84   25                  84            95       82   
3            82        90   30                  84            91       60   
4            91        90   31                  11            48       35   

   vision  jumping  strength  positioning  crossing  heading_accuracy  forvet  
0      85       95        80           95        85                88       1  
1      90       68        59           93        77                71       1  
2      80       61        53           90        75                62       1  
3      84       69        80           92        77                77       1  
4      70       78        83           12        15                25       0

In [9]:
df.columns

Index(['pas accuracy', 'shooting', 'age', 'free_kick_accuracy', 'ball_control',
       'balance', 'vision', 'jumping', 'strength', 'positioning', 'crossing',
       'heading_accuracy', 'forvet'],
      dtype='object')

In [10]:
X = df.iloc[:,0:12]
X.head()

pas accuracy  shooting  age  free_kick_accuracy  ball_control  balance  \
0            90        93   32                  76            93       63   
1            89        90   30                  90            95       95   
2            92        84   25                  84            95       82   
3            82        90   30                  84            91       60   
4            91        90   31                  11            48       35   

   vision  jumping  strength  positioning  crossing  heading_accuracy  
0      85       95        80           95        85                88  
1      90       68        59           93        77                71  
2      80       61        53           90        75                62  
3      84       69        80           92        77                77  
4      70       78        83           12        15                25

In [11]:
y = df.iloc[:,12:13]
y.head()

forvet
0       1
1       1
2       1
3       1
4       0

In [12]:
X=X.values
y=y.values

In [13]:
X = X.astype('float64')
X=scale(X)

In [14]:
y=y.flatten()

In [15]:
# Split the data
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.30)

# Make a new log_model
log_model = LogisticRegression()

# Now fit the new model
log_model.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
# Predict the classes of the testing data set
y_pred = log_model.predict(X_test)

# Compare the predicted classes to the actual test classes
print (metrics.accuracy_score(Y_test,y_pred))

0.9709205408408965


In [17]:
from sklearn.metrics import classification_report

print(classification_report(Y_test,y_pred))

             precision    recall  f1-score   support

          0       0.98      0.99      0.98      4917
          1       0.88      0.79      0.83       482

avg / total       0.97      0.97      0.97      5399



In [18]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [19]:
Y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
Y_test.size

5399

In [21]:
y_pred.size

5399

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, y_pred)

array([[4863,   54],
       [ 103,  379]], dtype=int64)

In [23]:
print(confusion_matrix)

<function confusion_matrix at 0x000002133AD7DEA0>
