In [20]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

import scipy
from scipy.stats import spearmanr

# Math
import math

# Plot imports
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

# Machine Learning Imports
from sklearn.preprocessing import scale
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split

# For evaluating our ML results
from sklearn import metrics

# Dataset Import
import statsmodels.api as sm

In [21]:
df = pd.read_csv('fifa_data2.csv')

In [22]:
df.head()

name  age                     league  height_cm  weight_kg  \
0  Cristiano Ronaldo   32  Spanish Primera División        185         80   
1           L. Messi   30  Spanish Primera División        170         72   
2             Neymar   25             French Ligue 1        175         68   
3         L. Suárez   30  Spanish Primera División        182         86   
4           M. Neuer   31          German Bundesliga        193         92   

   potential  pas accuracy  shooting  def  phy   ...    stamina  strength  \
0         94            90        93   33   80   ...         92        80   
1         93            89        90   26   61   ...         73        59   
2         94            92        84   30   60   ...         78        53   
3         92            82        90   42   81   ...         89        80   
4         92            91        90   60   91   ...         44        83   

   long_shots  aggression  interceptions  positioning  vision  penalties  \
0          92          63             29           95      85         85   
1          88          48             22           93      90         78   
2          77          56             36           90      80         81   
3          86          78             41           92      84         85   
4          16          29             30           12      70         47   

   composure  marking  
0         95       22  
1         96       13  
2         92       21  
3         83       30  
4         70       10  

[5 rows x 38 columns]

In [23]:
df = df[['pas accuracy', 'shooting','strength','heading_accuracy','finishing']]

In [24]:
df.head()

pas accuracy  shooting  strength  heading_accuracy  finishing
0            90        93        80                88         94
1            89        90        59                71         95
2            92        84        53                62         89
3            82        90        80                77         94
4            91        90        83                25         13

In [25]:
dfcopy=df.copy()
dfcopy = dfcopy.sample(frac=1).reset_index(drop=True)
df_sliced=df.head(300)

In [26]:
# Create check function
def forvet_check(x):
    if x >= 70:
        return 1
    else:
        return 0

# Apply to DataFrame
df_sliced['forvet'] = df_sliced['finishing'].apply(forvet_check)

C:\Users\egede\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [27]:
df_sliced=df_sliced.drop('finishing',axis=1)

In [28]:
df_sliced.head()

pas accuracy  shooting  strength  heading_accuracy  forvet
0            90        93        80                88       1
1            89        90        59                71       1
2            92        84        53                62       1
3            82        90        80                77       1
4            91        90        83                25       0

In [29]:
df_sliced.columns

Index(['pas accuracy', 'shooting', 'strength', 'heading_accuracy', 'forvet'], dtype='object')

In [30]:
X = df_sliced.iloc[:,0:4]
X.head()

pas accuracy  shooting  strength  heading_accuracy
0            90        93        80                88
1            89        90        59                71
2            92        84        53                62
3            82        90        80                77
4            91        90        83                25

In [31]:
y = df_sliced.iloc[:,4:5]
y.head()

forvet
0       1
1       1
2       1
3       1
4       0

In [32]:
X=X.values
y=y.values

In [33]:
X = X.astype('float64')
X=scale(X)

In [34]:
y=y.flatten()

In [35]:
# Split the data
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.30)

# Make a new log_model
log_model = LogisticRegression()

# Now fit the new model
log_model.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [36]:
# Predict the classes of the testing data set
y_pred = log_model.predict(X_test)

# Compare the predicted classes to the actual test classes
print (metrics.accuracy_score(Y_test,y_pred))

0.9


In [37]:
from sklearn.metrics import classification_report

print(classification_report(Y_test,y_pred))

             precision    recall  f1-score   support

          0       0.87      0.93      0.90        42
          1       0.93      0.88      0.90        48

avg / total       0.90      0.90      0.90        90



In [38]:
y_pred

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0], dtype=int64)

In [39]:
Y_test

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0], dtype=int64)

In [40]:
Y_test.size

90

In [41]:
y_pred.size

90

In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, y_pred)

array([[39,  3],
       [ 6, 42]], dtype=int64)

In [43]:
print(confusion_matrix)

<function confusion_matrix at 0x000001D64BBCCEA0>
